config/routes.rb
Rails.application.routes.draw do
  resources :students

end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
  end
  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to(new_student_path, :notice => "Student was created successfully")
    else
      render "new"
    end
  end

  def index
    @students = Student.all
  end


  private

  def student_params
    params.require(:student).permit!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>School</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/index.html.erb
<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th colspan="2" style="text-align: center">Action</th>
  </tr>
  <% @students.each do|student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.age %></td>
        <td>
          <%= link_to "Edit", edit_student_path(student), :class => 'btn btn-primary' %>
        </td>
        <td>
          <%= link_to "Delete", student_url(student), :method => :delete, :class => 'btn btn-danger', :confirm => "Are you sure?" %>
        </td>
      </tr>
  <% end %>
</table>
<%= link_to "New Student", new_student_url, :class => "btn btn-primary" %>

app/views/students/new.html.erb
<%= form_for @student, :html => { :class => 'form-horizontal', :role =>"form", :multipart => true } do |f| %>
    <%#= render :partial => "shared/errors", :locals => {:item => @product} %>
    <div class="form-group" style="margin-top: 10px">
      <%= f.label :name, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, :class => "form-control", :placeholder => "Title" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :age, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.number_field :age, :class => "form-control", :placeholder => "Age", :style => "height:100px" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit :class => "btn btn-default" %>
      </div>
    </div>
<% end %>